import urllib.request
import json

# 1. Fetch live GitHub stats
try:
    url = "https://api.github.com/users/hlcbabuyo"
    req = urllib.request.Request(url)
    with urllib.request.urlopen(req) as response:
        data = json.loads(response.read().decode())
        repos = data.get('public_repos', 0)
        followers = data.get('followers', 0)
except Exception:
    repos = "N/A"
    followers = "N/A"

# 2. Generate the CSS Animation Timestamps (Loops every 16 seconds)
# This controls exactly when each line appears and when they all vanish to restart.
css_animations = ""
steps = {
    'l1': 3,   # Appears at 3% of the 16s loop
    'l2': 10,  # Appears at 10%
    'l3': 18,  # etc...
    'l4': 25,
    'l5': 40,
    'l6': 47,
    'l7': 62,
    'l8': 69,
    'l9': 76
}

for class_name, start_pct in steps.items():
    css_animations += f".{class_name} {{ opacity: 0; animation: anim_{class_name} 16s infinite; }}\n"
    css_animations += f"@keyframes anim_{class_name} {{ 0%, {start_pct}% {{ opacity: 0; }} {start_pct + 0.1}%, 95% {{ opacity: 1; }} 95.1%, 100% {{ opacity: 0; }} }}\n"


# 3. Build the Animated, Pure Black Terminal SVG
svg_content = f"""<svg width="800" height="620" viewBox="0 0 800 620" xmlns="http://www.w3.org/2000/svg">
  <style>
    /* Pure Black Background */
    .bg {{ fill: #0A0A0A; }}
    
    /* Text Styles */
    .text {{ font-family: Consolas, 'Courier New', monospace; font-size: 15px; fill: #CCCCCC; }}
    .prompt {{ fill: #E06C75; }}
    .cyan {{ fill: #56B6C2; }}
    .green {{ fill: #98C379; }}
    .orange {{ fill: #D19A66; }}
    .blue {{ fill: #61AFEF; }}
    
    /* Blinking Cursor (Uses visibility so it doesn't fight the opacity animation) */
    .blink {{ animation: blinker 1s step-end infinite; }}
    @keyframes blinker {{ 50% {{ visibility: hidden; }} }}

    /* Line-by-line typing animations generated by Python */
    {css_animations}
  </style>

  <!-- Clean Black Terminal Background -->
  <rect width="100%" height="100%" class="bg"/>

  <!-- Terminal Content -->
  <g transform="translate(20, 30)">
    
    <!-- Boot Sequence -->
    <text x="0" y="0" class="text l1">Initializing terminal...</text>
    <text x="0" y="20" class="text l2"><tspan class="green">[OK]</tspan> System ready</text>

    <!-- Command 1: GitHub Stats -->
    <text x="0" y="60" class="text l3"><tspan class="prompt">hlcbabuyo@github</tspan> ~&gt; github-stats --user hlcbabuyo</text>
    
    <g class="l4">
        <text x="0" y="100" class="text cyan">=== GitHub Stats for hlcbabuyo ===</text>
        <text x="0" y="120" class="text"><tspan class="orange">Name:</tspan>        Harvie Lorenz C. Babuyo</text>
        <text x="0" y="140" class="text"><tspan class="orange">Role:</tspan>        Backend Systems Engineer</text>
        <text x="0" y="160" class="text"><tspan class="orange">Location:</tspan>    Tagoloan, Philippines</text>
        <text x="0" y="180" class="text"><tspan class="orange">Goal:</tspan>        240-Hour OJT (June 2026)</text>
        <text x="0" y="200" class="text"><tspan class="orange">Repos:</tspan>       {repos}</text>
        <text x="0" y="220" class="text"><tspan class="orange">Followers:</tspan>   {followers}</text>
        <text x="0" y="240" class="text cyan">==================================</text>
    </g>

    <!-- Command 2: Tech Stack -->
    <text x="0" y="280" class="text l5"><tspan class="prompt">hlcbabuyo@github</tspan> ~&gt; cat skills.txt</text>
    
    <g class="l6">
        <text x="0" y="320" class="text cyan">=== Tech Stack ===</text>
        <text x="0" y="340" class="text"><tspan class="blue">Backend:</tspan>     Python, FastAPI, SQLAlchemy, Pydantic</text>
        <text x="0" y="360" class="text"><tspan class="blue">Database:</tspan>    PostgreSQL, PostGIS, Redis</text>
        <text x="0" y="380" class="text"><tspan class="blue">Cloud:</tspan>       AWS (S3, EC2, RDS, IAM)</text>
        <text x="0" y="400" class="text"><tspan class="blue">DevOps:</tspan>      Docker, Git, GitHub Actions</text>
        <text x="0" y="420" class="text"><tspan class="blue">Processing:</tspan>  Celery, BeautifulSoup</text>
        <text x="0" y="440" class="text"><tspan class="blue">Tools:</tspan>       ReportLab, QRCode, boto3, Postman</text>
        <text x="0" y="460" class="text"><tspan class="blue">Languages:</tspan>   Python, SQL</text>
        <text x="0" y="480" class="text cyan">==================</text>
    </g>

    <!-- Command 3: The Outro -->
    <text x="0" y="520" class="text l7"><tspan class="prompt">hlcbabuyo@github</tspan> ~&gt; echo 'Thanks for visiting my profile!'</text>
    <text x="0" y="540" class="text green l8">Thanks for visiting my profile!</text>

    <!-- Final Prompt with Blinking Cursor -->
    <text x="0" y="580" class="text l9"><tspan class="prompt">hlcbabuyo@github</tspan> ~&gt; <tspan class="blink">█</tspan></text>
  </g>
</svg>"""

with open("terminal.svg", "w", encoding="utf-8") as file:
    file.write(svg_content)

print("Infinite looping animated SVG generated successfully!")
